<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Opening hours_reset--button</name>
   <tag></tag>
   <elementGuidId>00790a2b-bd13-412a-ad06-26e5e111da67</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.reset--button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='stickyNavContainer']/section[2]/div/div/div/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1b254cdf-517e-4855-934d-2d65532033e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>8ba2784e-8605-42b9-b6b3-e394e6eba0ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>menuButton0</value>
      <webElementGuid>d2270279-c8f2-4718-aeb2-e709ee51b599</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>71e80f6c-79bf-4db5-9746-c4242b61410e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Open Opening hours menu</value>
      <webElementGuid>9208ee03-18f9-45c8-8fda-ebabf5894f6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>reset--button</value>
      <webElementGuid>0a6f1bd4-901b-4e30-90df-268f6a81da73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;stickyNavContainer&quot;)/section[@class=&quot;page-section opening-hours&quot;]/div[@class=&quot;opening-hours__list&quot;]/div[@class=&quot;drop-button__wrapper&quot;]/div[@class=&quot;drop-button&quot;]/button[@class=&quot;reset--button&quot;]</value>
      <webElementGuid>370f6d26-f789-45c9-950a-08807eda7ddf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='stickyNavContainer']/section[2]/div/div/div/button</value>
      <webElementGuid>a70e1c34-d2f8-428e-9208-28064e951c30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[2]/div/div/div/button</value>
      <webElementGuid>ed1995c6-6556-41fe-b446-c5a87897fb4e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
