<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_Opening hours</name>
   <tag></tag>
   <elementGuidId>243147d4-4498-455a-b229-f37176b9cfef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#opening-hours</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//h2[@id='opening-hours']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>4f29d1ec-4035-4e02-ad24-d974b638d442</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>opening-hours</value>
      <webElementGuid>8e7cb5c4-5d29-4609-8150-2c47b7ddad24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>930b24b6-153f-4830-b87c-d061994bf603</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Opening hours</value>
      <webElementGuid>5dc8a363-cd65-4215-9dc6-7a7d5e96c53e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;opening-hours&quot;)</value>
      <webElementGuid>2a80fbc1-1852-4439-bb1d-7eeca7cf459b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h2[@id='opening-hours']</value>
      <webElementGuid>5dba974a-8d7a-4464-b765-ad9fdf54efed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='stickyNavContainer']/section[2]/h2</value>
      <webElementGuid>e926b644-de25-41ed-8259-05b939dd1eb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Marrickville Service Centre'])[1]/following::h2[1]</value>
      <webElementGuid>d37a8cc3-733e-4f37-bd12-8f4efd15a320</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Botany Service Centre'])[1]/following::h2[1]</value>
      <webElementGuid>e79baf26-be9e-4027-8fdd-544eb59da4c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='this week'])[1]/preceding::h2[1]</value>
      <webElementGuid>f2a788fc-0e0f-4ed6-bc12-5789838e1f6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='next week'])[1]/preceding::h2[1]</value>
      <webElementGuid>064a0041-c778-4edf-9cc0-53ccf8f8cd62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[2]/h2</value>
      <webElementGuid>90aaa9fc-6dcf-4248-9703-988c684da72c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[@id = 'opening-hours' and (text() = 'Opening hours' or . = 'Opening hours')]</value>
      <webElementGuid>54fa6335-9aac-472d-adb1-fd9b108824a5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
