<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Find locations</name>
   <tag></tag>
   <elementGuidId>85e55b32-0a51-4117-8aef-bea0fb7a1ab3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='global-header']/div/header/div[2]/div/nav/ul/li[4]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3b6c8e03-1f6e-4bb1-a879-b99339f78f83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.service.nsw.gov.au/service-centre</value>
      <webElementGuid>d7301be1-84a4-4394-9ad9-bf4579340c30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>NavLink__link-M-HSy9SYcc</value>
      <webElementGuid>b8d7c069-5ae9-4e84-b9cb-c0384c226337</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Find locations</value>
      <webElementGuid>ba070b6c-4481-4482-a1e9-998c5d830573</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;global-header&quot;)/div[1]/header[@class=&quot;GlobalHeader-0xZ4-w1g3x&quot;]/div[@class=&quot;GlobalHeader__main-ORzg9dkzx0&quot;]/div[@class=&quot;Container-f-hqve2slU GlobalHeader__mainContainer-jduh-JKthi&quot;]/nav[@class=&quot;MainNav-AYWEJogDLj&quot;]/ul[@class=&quot;MainNav__list-peZtddYtxn&quot;]/li[@class=&quot;NavLink__listItem-VYVwsaNaTG&quot;]/a[@class=&quot;NavLink__link-M-HSy9SYcc&quot;]</value>
      <webElementGuid>003827a4-6cad-47ef-b553-97ce83bb56ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c967dc5d-0923-4434-90e5-3d40ee248568</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.service.nsw.gov.au/service-centre</value>
      <webElementGuid>63e27a91-623b-4b9b-b447-a94724b4f57e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>NavLink__link-M-HSy9SYcc</value>
      <webElementGuid>3b930e1c-e3c7-4a1c-9d0c-461b268879ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Find locations</value>
      <webElementGuid>89a2d630-4850-4890-a78a-4a5b16570b5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;global-header&quot;)/div[1]/header[@class=&quot;GlobalHeader-0xZ4-w1g3x&quot;]/div[@class=&quot;GlobalHeader__main-ORzg9dkzx0&quot;]/div[@class=&quot;Container-f-hqve2slU GlobalHeader__mainContainer-jduh-JKthi&quot;]/nav[@class=&quot;MainNav-AYWEJogDLj&quot;]/ul[@class=&quot;MainNav__list-peZtddYtxn&quot;]/li[@class=&quot;NavLink__listItem-VYVwsaNaTG&quot;]/a[@class=&quot;NavLink__link-M-HSy9SYcc&quot;]</value>
      <webElementGuid>f0926349-3378-43f5-b32b-9ea15f639de2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>71084ca2-c0d1-4381-8007-d9fdb08581e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.service.nsw.gov.au/service-centre</value>
      <webElementGuid>3f29b0a6-8e2e-4b4f-bd00-7b08b0a02db8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>NavLink__link-M-HSy9SYcc</value>
      <webElementGuid>a413feee-cf92-4765-91e7-7a70a80cb290</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Find locations</value>
      <webElementGuid>dafe15ad-9e36-4bf1-9790-d589bed0126b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;global-header&quot;)/div[1]/header[@class=&quot;GlobalHeader-0xZ4-w1g3x&quot;]/div[@class=&quot;GlobalHeader__main-ORzg9dkzx0&quot;]/div[@class=&quot;Container-f-hqve2slU GlobalHeader__mainContainer-jduh-JKthi&quot;]/nav[@class=&quot;MainNav-AYWEJogDLj&quot;]/ul[@class=&quot;MainNav__list-peZtddYtxn&quot;]/li[@class=&quot;NavLink__listItem-VYVwsaNaTG&quot;]/a[@class=&quot;NavLink__link-M-HSy9SYcc&quot;]</value>
      <webElementGuid>7cc9fd03-08a3-4c4d-807e-a409f6ca431e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='global-header']/div/header/div[2]/div/nav/ul/li[4]/a</value>
      <webElementGuid>b8069d5f-cbbd-4bcf-9bab-6fa93921cf20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Find locations')]</value>
      <webElementGuid>398a905e-8b1f-4712-b3f6-0c9e5c4b1883</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Business'])[1]/following::a[1]</value>
      <webElementGuid>d9bda584-0878-40cd-aab5-dd2a95de716f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Browse services'])[1]/following::a[2]</value>
      <webElementGuid>1bb12148-66e2-4905-9fdb-0043a73f5d1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[2]/preceding::a[1]</value>
      <webElementGuid>0ccf13cf-cb72-4bc6-b1eb-e873eb4f87ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Browse services'])[2]/preceding::a[2]</value>
      <webElementGuid>f721d767-58d5-4bc3-81ae-1bb14f64fc92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Find locations']/parent::*</value>
      <webElementGuid>33ce43c7-e012-4c0d-bf0b-8cba2fd453c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.service.nsw.gov.au/service-centre')]</value>
      <webElementGuid>956e8454-e856-4cc4-be0a-f37611bec36f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/a</value>
      <webElementGuid>e5ef8892-85f4-4557-8047-d432ddb232d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.service.nsw.gov.au/service-centre' and (text() = 'Find locations' or . = 'Find locations')]</value>
      <webElementGuid>1029d62d-d31b-4045-ad73-a35252abc638</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
