<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Marrickville Service Centre</name>
   <tag></tag>
   <elementGuidId>83099977-868f-4d51-8663-5816f0af9d58</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='locatorListView']/div/div/div[6]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>258d96b0-d7f1-461e-85c6-1c9e8d420afe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>location__title</value>
      <webElementGuid>e7ec997d-717b-4d64-b474-4a3b2bf46e8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/service-centre/marrickville-service-centre</value>
      <webElementGuid>78a3e299-5384-4daa-b743-6ca36f1de63e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Marrickville Service Centre </value>
      <webElementGuid>56d214ca-4eee-4427-bd83-9316b0168331</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;locatorListView&quot;)/div[@class=&quot;locator__results&quot;]/div[@class=&quot;locator__results-list&quot;]/div[@class=&quot;location&quot;]/a[@class=&quot;location__title&quot;]</value>
      <webElementGuid>65d0c0be-efe6-4a21-841f-59761faf59e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>96093635-175b-4910-ac41-43183a27d865</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>location__title</value>
      <webElementGuid>76c818e0-5b88-4958-92d5-0e1af978a0fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/service-centre/marrickville-service-centre</value>
      <webElementGuid>ba043cae-b6f2-4ade-bfce-c0f235bdbb81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Marrickville Service Centre </value>
      <webElementGuid>2bdfafe5-8eac-4284-8acb-0b635fd55156</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;locatorListView&quot;)/div[@class=&quot;locator__results&quot;]/div[@class=&quot;locator__results-list&quot;]/div[@class=&quot;location&quot;]/a[@class=&quot;location__title&quot;]</value>
      <webElementGuid>db859c55-d467-4388-aea1-411138aaf73f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='locatorListView']/div/div/div[6]/a</value>
      <webElementGuid>1d868e71-0385-4aca-a7b7-1ee5a9486580</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Marrickville Service Centre')]</value>
      <webElementGuid>9f34c251-730f-421a-b628-9f625a359e20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Open 8:30am to 5pm'])[3]/following::a[1]</value>
      <webElementGuid>7dbe2685-55f7-4635-8e6f-ee27a1c8b6ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bondi Junction Service Centre'])[1]/following::a[1]</value>
      <webElementGuid>43e5430a-3cd1-4a2d-9204-d136323fbec7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Open 9am to 5:30pm'])[1]/preceding::a[1]</value>
      <webElementGuid>18bbf366-b895-44a7-9087-42c199d392a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='To navigate, press the arrow keys.'])[1]/preceding::a[1]</value>
      <webElementGuid>ffa676a4-2db1-4cbf-9dc9-e62210db10a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Marrickville Service Centre']/parent::*</value>
      <webElementGuid>3783f321-eff4-47db-9445-80f16a7af02f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/service-centre/marrickville-service-centre')]</value>
      <webElementGuid>9313e99c-8a8d-4fc5-bae6-4b00fbb764cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/a</value>
      <webElementGuid>89894b05-269e-4da0-888f-50e7a24c6f27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/service-centre/marrickville-service-centre' and (text() = 'Marrickville Service Centre ' or . = 'Marrickville Service Centre ')]</value>
      <webElementGuid>5c481e39-b858-4c0f-a805-9098d396986a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
