<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>svg</name>
   <tag></tag>
   <elementGuidId>1bb517e8-b888-42a1-b9a0-f13d5d440471</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.button.button--primary.button--xxlarge > svg</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Sydney South 2000'])[1]/following::*[name()='svg'][2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>5afd846a-6ba9-441c-8d20-ce692f3d61d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>31</value>
      <webElementGuid>065a7974-1a4a-43c8-9aa0-73aa4ecadc5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>32</value>
      <webElementGuid>e612827f-ce6e-4edd-bdc4-27ab0ded1583</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 31 32</value>
      <webElementGuid>b30739f2-bf52-4aa1-bc16-edd2352fb9a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns</name>
      <type>Main</type>
      <value>http://www.w3.org/2000/svg</value>
      <webElementGuid>012ad8c3-42d8-4d6c-9c14-ed01fc8176bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;locator&quot;)/div[@class=&quot;locator&quot;]/form[@class=&quot;locator__search&quot;]/div[@class=&quot;suburb-suggest&quot;]/div[@class=&quot;form__input-group form--search-group&quot;]/div[@class=&quot;form__actions&quot;]/div[@class=&quot;form__actions&quot;]/button[@class=&quot;button button--primary button--xxlarge&quot;]/svg[1]</value>
      <webElementGuid>ce22d2f3-4d15-4e4d-b14b-d693e70349fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>f56876ee-256b-41c1-893b-44124c310dc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>31</value>
      <webElementGuid>65149670-c125-402c-9b25-3a7ae02854fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>32</value>
      <webElementGuid>9c9c843c-d94a-43ec-8c1f-0ee0cb1e35b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 31 32</value>
      <webElementGuid>c42d3f7a-0221-49c4-ad7f-29ea1980f6ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns</name>
      <type>Main</type>
      <value>http://www.w3.org/2000/svg</value>
      <webElementGuid>4912f059-8dbd-4f0c-8d6b-b4013c25d289</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;locator&quot;)/div[@class=&quot;locator&quot;]/form[@class=&quot;locator__search&quot;]/div[@class=&quot;suburb-suggest&quot;]/div[@class=&quot;form__input-group form--search-group&quot;]/div[@class=&quot;form__actions&quot;]/div[@class=&quot;form__actions&quot;]/button[@class=&quot;button button--primary button--xxlarge&quot;]/svg[1]</value>
      <webElementGuid>c59bb331-8457-48ec-a1a8-46e9921b95da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>b57bea4f-0a07-4b58-9092-be4c8554aa36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>31</value>
      <webElementGuid>97796055-8fa8-4766-a620-97cc6e34ea82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>32</value>
      <webElementGuid>15a00f05-136a-41c6-8a56-9f3f60aafd7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 31 32</value>
      <webElementGuid>0a88d56a-99db-480c-b8ee-95059a803298</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns</name>
      <type>Main</type>
      <value>http://www.w3.org/2000/svg</value>
      <webElementGuid>542321e1-ecc3-4992-9890-dee095592464</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;locator&quot;)/div[@class=&quot;locator&quot;]/form[@class=&quot;locator__search&quot;]/div[@class=&quot;suburb-suggest&quot;]/div[@class=&quot;form__input-group form--search-group&quot;]/div[@class=&quot;form__actions&quot;]/div[@class=&quot;form__actions&quot;]/button[@class=&quot;button button--primary button--xxlarge&quot;]/svg[1]</value>
      <webElementGuid>4e5ed193-b2fa-4528-9461-a42968e852ac</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sydney South 2000'])[1]/following::*[name()='svg'][2]</value>
      <webElementGuid>db0c1320-99af-40f7-beb5-a8666e44888c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sydney 2000'])[1]/following::*[name()='svg'][2]</value>
      <webElementGuid>3ed64fe9-2975-49e0-8c98-6a0dd66aabbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Filter by centre type'])[1]/preceding::*[name()='svg'][1]</value>
      <webElementGuid>24146175-0a51-490e-8b39-fefa97106fe5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All'])[1]/preceding::*[name()='svg'][1]</value>
      <webElementGuid>080c84d5-f92a-416e-b2d8-5e6969f3c376</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sydney Domestic Airport 2020'])[1]/following::*[name()='svg'][2]</value>
      <webElementGuid>7f862661-559f-4157-845c-f74ab11319bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search by suburb, postcode or current location'])[1]/following::*[name()='svg'][2]</value>
      <webElementGuid>9fdbbdad-b9f8-4479-80cf-b40158eb6334</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
